###############################################################################
#        Generated on phpdocker.io and edited by Benj                         #
###############################################################################

benjaminlierman-memcached:
  image: phpdockerio/memcached:latest
  container_name: benjaminlierman-memcached

benjaminlierman-mysql:
  image: mysql:5.7
  container_name: benjaminlierman-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=benjaminlierman
    - MYSQL_USER=benjaminlierman
    - MYSQL_PASSWORD=root
  ports:
    - 3306:3306
  volumes:
    - ../www/data/mysql:/var/lib/mysql

benjaminlierman-webserver:
  image: phpdockerio/nginx:latest
  container_name: benjaminlierman-webserver
  volumes:
      - ../www:/var/www/benjaminlierman
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - benjaminlierman-php-fpm

benjaminlierman-php-fpm:
  image: bensji/php-fpm
  container_name: benjaminlierman-php-fpm
  volumes:
    - ../www:/var/www/benjaminlierman
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - benjaminlierman-memcached
    - benjaminlierman-mysql
